/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AfterSQLfix.BookStore_Final;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
/**
 *
 * @author Manimozhi Ramalingam
 */
public class BookStoreMain extends javax.swing.JFrame {
    
    static Connection con;

    /**
     * Creates new form GettingBooksFrame
     */
    public BookStoreMain() {
        initComponents();
        setTitle("Book Store");
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection conHome = DriverManager.getConnection("jdbc:derby://localhost:1527/MiniProject_BookStore","gova","gova");
            PreparedStatement stHome = conHome.prepareStatement("select * from gova.images where Name='BookStore'");
            ResultSet rsetHome = stHome.executeQuery();
            rsetHome.next();
            homeFirstLab.setText("");
            homeFirstLab.setBackground(new Color(0,0,128));
            BufferedImage im = ImageIO.read(rsetHome.getBinaryStream(2));
            homeFirstLab.setIcon(new ImageIcon(im)); 
            mainPanel.add(homeFirstLab, BorderLayout.CENTER);
            System.out.println("HomeFirstLab size : "+homeFirstLab.getSize().toString());
        } catch(Exception exc) {
            System.out.println("Exception during HomeImage making : "+exc);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsPanel = new javax.swing.JPanel();
        homeLabBut = new javax.swing.JLabel();
        iconLab = new javax.swing.JLabel();
        categLabBut = new javax.swing.JLabel();
        cartLabBut = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchTxtf = new javax.swing.JTextField();
        searchBut = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        homeFirstLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Store");

        optionsPanel.setBackground(new java.awt.Color(65, 105, 225));
        optionsPanel.setName(""); // NOI18N

        homeLabBut.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        homeLabBut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLabBut.setText("Home");
        homeLabBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        homeLabBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeLabButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeLabButMouseExited(evt);
            }
        });

        iconLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AfterSQLfix/bookIconRZD.jpg"))); // NOI18N

        categLabBut.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        categLabBut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        categLabBut.setText("Categories");
        categLabBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categLabButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categLabButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                categLabButMouseExited(evt);
            }
        });

        cartLabBut.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        cartLabBut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartLabBut.setText("Cart");
        cartLabBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartLabButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cartLabButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cartLabButMouseExited(evt);
            }
        });

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionsPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cartLabBut, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(homeLabBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(categLabBut, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))))
                    .addGroup(optionsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconLab)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconLab, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(homeLabBut)
                .addGap(103, 103, 103)
                .addComponent(categLabBut)
                .addGap(101, 101, 101)
                .addComponent(cartLabBut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchPanel.setBackground(new java.awt.Color(112, 202, 238));

        searchTxtf.setBackground(new java.awt.Color(204, 255, 204));
        searchTxtf.setFont(new java.awt.Font("Centaur", 0, 22)); // NOI18N
        searchTxtf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchTxtf.setText("Search books here");
        searchTxtf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        searchTxtf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTxtfMouseClicked(evt);
            }
        });
        searchTxtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtfActionPerformed(evt);
            }
        });

        searchBut.setFont(new java.awt.Font("Californian FB", 1, 20)); // NOI18N
        searchBut.setText("Search");
        searchBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        searchBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBut, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxtf, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBut, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(0, 191, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        homeFirstLab.setFont(new java.awt.Font("Tw Cen MT", 0, 45)); // NOI18N
        homeFirstLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeFirstLab.setText("Welcome to the vast world of books !");
        homeFirstLab.setOpaque(true);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(homeFirstLab, javax.swing.GroupLayout.PREFERRED_SIZE, 1196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(homeFirstLab, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );

        mainPanel.getAccessibleContext().setAccessibleParent(searchPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTxtfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTxtfMouseClicked
        // TODO add your handling code here:
        searchTxtf.setText("");
    }//GEN-LAST:event_searchTxtfMouseClicked

    private void searchTxtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtfActionPerformed

    private void searchButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        System.out.println("Search Button clicked");
      
        String x = searchTxtf.getText();
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/MiniProject_BookStore","gova","gova");
            PreparedStatement ps = con.prepareStatement("SELECT * FROM gova.allbooks where title='"+x+"' or author='"+x+"'",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            //Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rest = ps.executeQuery();
            if(!rest.first()) {
                System.out.println("No books found");
                JOptionPane.showMessageDialog(rootPane, "No books found");
                return;
            }
            rest.beforeFirst();
            int rowCount = rest.last() ? rest.getRow() : 0;
            System.out.println("Row count : "+rowCount);
            
            DefaultTableModel defaultTableModel = new DefaultTableModel();
            JTable Resultstable = new JTable(defaultTableModel);
            Resultstable.setSize(1375, 750);
            Resultstable.setPreferredScrollableViewportSize(new Dimension(1370, 745));
            Resultstable.setFillsViewportHeight(true);
            Resultstable.setFont(new Font("Book Antiqua", Font.PLAIN, 20));
            Resultstable.setRowHeight(50);
            JTableHeader tableHeader = Resultstable.getTableHeader();
            Font tableHeadFont = new Font("Book Antiqua",Font.BOLD, 26);
            tableHeader.setForeground(Color.blue);
            tableHeader.setBackground(Color.cyan);
            tableHeader.setFont(tableHeadFont);
            mainPanel.add(new JScrollPane(Resultstable));
            defaultTableModel.addColumn("Title");
            defaultTableModel.addColumn("Author");
            defaultTableModel.addColumn("Cost");
            Resultstable.getColumn("Title").setPreferredWidth(550);
            mainPanel.setLayout(new GridLayout(1,1));
            
            rest.beforeFirst();
            while(rest.next()) {
                    System.out.println(rest.getString(1)+"\t\t"+rest.getString(2)+"\t\t"+rest.getString(3));
                    String bTitle = rest.getString(2);
                    String bAuthor = rest.getString(3);
                    Double bPrice = rest.getDouble(4);

                    defaultTableModel.addRow(new Object[]{bTitle,bAuthor,"Rs. "+bPrice});               
            }
            Resultstable.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent e) {
                    try {
                    int row=Resultstable.rowAtPoint(e.getPoint());
                    int col=0;
                    BookView bv1 = new BookView(rest, con, defaultTableModel.getValueAt(row, col).toString());
                    bv1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);                            
                    bv1.setVisible(true);
                    } catch(ArrayIndexOutOfBoundsException exc) {
                        System.out.println("Clicked outside the table");
                    }
                }
            });
            SwingUtilities.updateComponentTreeUI(this);
//            setVisible(false);
//            setVisible(true);
            
        } catch(SQLException exc) {
            System.out.println("Place 1 :");
            exc.printStackTrace();
        } catch(IndexOutOfBoundsException e2) {
            System.out.println("Place 2 :");
            System.out.println(e2);
          //  e2.printStackTrace();
        } catch(Exception ex) {
            System.out.println("Place 3 Common :");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_searchButActionPerformed

    private void homeLabButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabButMouseClicked
        // TODO add your handling code here:
        //System.out.println("Home : Clicked");
        mainPanel.removeAll();
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection conHome = DriverManager.getConnection("jdbc:derby://localhost:1527/MiniProject_BookStore","gova","gova");
            PreparedStatement stHome = conHome.prepareStatement("select * from gova.images where Name='BookStore'");
            ResultSet rsetHome = stHome.executeQuery();
            rsetHome.next();
            homeFirstLab.setText("");
            homeFirstLab.setBackground(new Color(0,195,255));
            BufferedImage im = ImageIO.read(rsetHome.getBinaryStream(2));
            homeFirstLab.setIcon(new ImageIcon(im)); 
            mainPanel.add(homeFirstLab, BorderLayout.CENTER);
        } catch(Exception exc) {
            System.out.println("Exception during HomeImage making : "+exc);
        }
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_homeLabButMouseClicked

    private void homeLabButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabButMouseEntered
        // TODO add your handling code here:
        homeLabBut.setForeground(Color.LIGHT_GRAY);
        //System.out.println("Home : Mouse entered");
    }//GEN-LAST:event_homeLabButMouseEntered

    private void homeLabButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabButMouseExited
        // TODO add your handling code here:
        homeLabBut.setForeground(Color.black);
        //System.out.println("Home : Mouse exited");
    }//GEN-LAST:event_homeLabButMouseExited

    private void categLabButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categLabButMouseEntered
        // TODO add your handling code here:
        categLabBut.setForeground(Color.LIGHT_GRAY);
        //System.out.println("Categories : Mouse entered");
    }//GEN-LAST:event_categLabButMouseEntered

    private void categLabButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categLabButMouseExited
        // TODO add your handling code here:
        categLabBut.setForeground(Color.black);
        //System.out.println("Categories : Mouse exited");
    }//GEN-LAST:event_categLabButMouseExited

    private void categLabButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categLabButMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.setLayout(new CardLayout());
        //System.out.println("Categories : Clicked");
        CategoryPanel catPanel = new CategoryPanel();
        mainPanel.add(catPanel);
        catPanel.setVisible(true);
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_categLabButMouseClicked

    private void cartLabButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartLabButMouseEntered
        // TODO add your handling code here:
        cartLabBut.setForeground(Color.LIGHT_GRAY);
        //System.out.println("Cart : Mouse entered");
    }//GEN-LAST:event_cartLabButMouseEntered

    private void cartLabButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartLabButMouseExited
        // TODO add your handling code here:
        cartLabBut.setForeground(Color.black);
        //System.out.println("Cart : Mouse exited");
    }//GEN-LAST:event_cartLabButMouseExited
    
    private void cartLabButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartLabButMouseClicked
        // TODO add your handling code here:
        //System.out.println("Cart : Clicked");
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/MiniProject_BookStore","gova","gova");
            PreparedStatement psCart = con.prepareStatement("SELECT * FROM gova.cart",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rest = psCart.executeQuery();
            if(!rest.first()) {
                System.out.println("Cart is empty");
                JOptionPane.showMessageDialog(rootPane, "Cart is empty");
                return;
            }
            mainPanel.removeAll();
            rest.beforeFirst();
            int rowCount = rest.last() ? rest.getRow() : 0;
            System.out.println("Row count : "+rowCount);          
            
            mainPanel.setLayout(new BorderLayout());
            DefaultTableModel defaultTableModelCart = new DefaultTableModel();
            JTable cartTable = new JTable(defaultTableModelCart);
            cartTable.setSize(1375, 680);
            cartTable.setPreferredScrollableViewportSize(new Dimension(1370, 680));
            cartTable.setFillsViewportHeight(true);
            cartTable.setFont(new Font("Book Antiqua", Font.PLAIN, 20));
            cartTable.setRowHeight(50);
            JTableHeader tableHeader = cartTable.getTableHeader();
            Font tableHeadFont = new Font("Book Antiqua",Font.BOLD, 26);
            tableHeader.setForeground(Color.blue);
            tableHeader.setBackground(Color.cyan);
            tableHeader.setFont(tableHeadFont);
            mainPanel.add(new JScrollPane(cartTable), BorderLayout.NORTH);
            defaultTableModelCart.addColumn("Title");
            defaultTableModelCart.addColumn("Author");
            defaultTableModelCart.addColumn("Cost");
            cartTable.getColumn("Title").setPreferredWidth(550);

            rest.beforeFirst();
            while(rest.next()) {
                System.out.println("Row : "+rest.getRow());
                long isbn = rest.getLong(1);
                PreparedStatement ps2 = con.prepareStatement("select * from gova.allbooks where isbn=?",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                ps2.setLong(1, isbn);
                ResultSet rset2=ps2.executeQuery();
                rset2.next();
                String title = rset2.getString(2);
                String author = rset2.getString(3);
                Double price = rset2.getDouble(4);
                Long cartISBN = rset2.getLong(1);
                defaultTableModelCart.addRow(new Object[]{title,author,"Rs. "+price});
            }
            cartTable.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent e) {
                    try {
                        PreparedStatement psAllBooks = con.prepareStatement("SELECT * FROM gova.allbooks",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                        ResultSet rsetCart = psAllBooks.executeQuery();
                        int row=cartTable.rowAtPoint(e.getPoint());
                        int col=0;
                        String cartTitle = defaultTableModelCart.getValueAt(row, col).toString();
                        PreparedStatement psCart = con.prepareStatement("delete from gova.cart where isbn=?");
                        int x = JOptionPane.showConfirmDialog(null, "Do you wish to remove this book from the cart ?","Cart", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (x == JOptionPane.YES_OPTION) {
                            while(rsetCart.next()) {
                                if(rsetCart.getString(2).equals(cartTitle)){
                                    long isbn = rsetCart.getLong(1);
                                    psCart.setLong(1, isbn);
                                    psCart.executeUpdate();
                                    System.out.println(cartTitle+" successfully removed from Cart");
                                }
                            }
                            defaultTableModelCart.removeRow(row);
                        }
                    } catch(ArrayIndexOutOfBoundsException exc) {
                        System.out.println("Clicked outside the table");
                    } catch(SQLException sqlEx) {
                        System.out.println("SQL Exception : "+sqlEx);
                    }
                }
            });
            JPanel buyPane = new JPanel();
            JButton buyBut = new JButton("Buy");
            buyBut.setFont(new Font("Copperplate Golith",Font.BOLD,20));
            buyPane.add(buyBut, BorderLayout.CENTER);
            mainPanel.add(buyPane, BorderLayout.SOUTH);          
            buyBut.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    System.out.println("Buy Button was clicked ");
                    BuyFrame buy1 = new BuyFrame();
                    buy1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    buy1.setVisible(true);
                    
                    try {
                        ResultSet rset2 = psCart.executeQuery(); // gets cart items
                        while(rset2.next()) {
                            long isbn = rset2.getLong(1);
                            PreparedStatement psAllBooks2 = con.prepareStatement("SELECT * FROM gova.allbooks where isbn="+isbn+"",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                            ResultSet rsetBook = psAllBooks2.executeQuery();
                            rsetBook.next();
                            int stock = rsetBook.getInt(10);
                            stock = stock-1;
                            PreparedStatement psStack = con.prepareStatement("UPDATE GOVA.ALLBOOKS SET stock="+stock+" WHERE ISBN="+isbn+"");
                            psStack.executeUpdate();
                        }
                    } catch(SQLException ex) {
                        System.out.println("SQL Exception when decrementing stock : "+ex);
                    }
                }
            });
            SwingUtilities.updateComponentTreeUI(this);
        } catch(Exception exc) {
            System.out.println("Exception while showing cart : "+exc);
        }
    }//GEN-LAST:event_cartLabButMouseClicked
    void cartResultsLabMouseClicked(java.awt.event.MouseEvent evt, ResultSet rset, Connection con, String s) {
        BookView bv2 = new BookView(rset, con, s);
        bv2.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);                            
        bv2.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookStoreMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookStoreMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookStoreMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookStoreMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BookStoreMain bookStore = new BookStoreMain();
                bookStore.setVisible(true);
                bookStore.setResizable(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cartLabBut;
    private javax.swing.JLabel categLabBut;
    private javax.swing.JLabel homeFirstLab;
    private javax.swing.JLabel homeLabBut;
    private javax.swing.JLabel iconLab;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JButton searchBut;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTxtf;
    // End of variables declaration//GEN-END:variables
}
