/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AfterSQLfix.BookStore_Final;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.*;

public class BookView extends javax.swing.JFrame {

    /**
     * Creates new form BookView
     */
    public BookView(ResultSet rset, Connection con1, String bID) {
        initComponents();
        try {
            rset.beforeFirst();
            while(rset.next()) {
                if(rset.getString(2).equals(bID)) {
                    setTitle(rset.getString(2));
                    titleStuff.setText(""+rset.getString(2));
                    authorStuff.setText(""+rset.getString(3));
                    priceStuff.setText("Rs. "+rset.getDouble(4));
                    isbnStuff.setText(""+rset.getString(1));
                    publisherStuff.setText(""+rset.getString(5));
                    publishDateStuff.setText(""+rset.getDate(6));
                    genreStuff.setText(""+rset.getString(7));                               
                    BufferedImage im = ImageIO.read(rset.getBinaryStream(9));
                    coverIcon.setIcon(new ImageIcon(im));
                    long isbn = rset.getLong(1);                            
                    addToCartBut.addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent ae) {
                            try {
                                PreparedStatement ps = con1.prepareStatement("SELECT * FROM GOVA.ALLBOOKS WHERE title=?",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                                ps.setString(1, bID);
                                ResultSet rset = ps.executeQuery();
                                rset.next();
                                int stock = rset.getInt(10);
                                if(stock==0) {
                                    JOptionPane.showMessageDialog(rootPane, "This book is out of stock", "Book Out Of Stock", JOptionPane.INFORMATION_MESSAGE);
                                    return;
                                }
                                AddingToCart add1 = new AddingToCart(isbn);
                            } catch(SQLException ex) {
                                System.out.println("SQLException when checking stock : "+ex);
                            }
                        }
                    });
                }
                 SwingUtilities.updateComponentTreeUI(this);
            }
        } catch(SQLException SQlexc) {
            System.out.println("SQL exception : ");
            SQlexc.printStackTrace();
        } catch(Exception exc) {
            System.out.println("General exception : "+exc);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bookViewPanel = new javax.swing.JPanel();
        coverIcon = new javax.swing.JLabel();
        titleLab = new javax.swing.JLabel();
        authorLab = new javax.swing.JLabel();
        priceLab = new javax.swing.JLabel();
        publishLab = new javax.swing.JLabel();
        publishDateLab = new javax.swing.JLabel();
        addToCartBut = new javax.swing.JButton();
        isbnLab = new javax.swing.JLabel();
        genreLab = new javax.swing.JLabel();
        titleStuff = new javax.swing.JLabel();
        authorStuff = new javax.swing.JLabel();
        isbnStuff = new javax.swing.JLabel();
        priceStuff = new javax.swing.JLabel();
        publisherStuff = new javax.swing.JLabel();
        publishDateStuff = new javax.swing.JLabel();
        genreStuff = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bookViewPanel.setBackground(new java.awt.Color(135, 206, 250));

        coverIcon.setBackground(new java.awt.Color(255, 255, 255));
        coverIcon.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 30)); // NOI18N
        coverIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coverIcon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        coverIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        titleLab.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        titleLab.setForeground(new java.awt.Color(0, 0, 205));
        titleLab.setText("Title : ");
        titleLab.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        authorLab.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        authorLab.setForeground(new java.awt.Color(0, 0, 205));
        authorLab.setText("Author :");
        authorLab.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        priceLab.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        priceLab.setForeground(new java.awt.Color(0, 0, 205));
        priceLab.setText("Price : ");
        priceLab.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        publishLab.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        publishLab.setForeground(new java.awt.Color(0, 0, 205));
        publishLab.setText("Publisher : ");
        publishLab.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        publishDateLab.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        publishDateLab.setForeground(new java.awt.Color(0, 0, 205));
        publishDateLab.setText("Date of Publication :");
        publishDateLab.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        addToCartBut.setFont(new java.awt.Font("Century Schoolbook", 1, 20)); // NOI18N
        addToCartBut.setText("Add To Cart");
        addToCartBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addToCartBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartButActionPerformed(evt);
            }
        });

        isbnLab.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        isbnLab.setForeground(new java.awt.Color(0, 0, 205));
        isbnLab.setText("ISBN :");
        isbnLab.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        genreLab.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        genreLab.setForeground(new java.awt.Color(0, 0, 205));
        genreLab.setText("Genre : ");
        genreLab.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        titleStuff.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        titleStuff.setText("Title goes here");

        authorStuff.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        authorStuff.setText("Author goes here");

        isbnStuff.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        isbnStuff.setText("ISBN goes here");

        priceStuff.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        priceStuff.setText("Price goes here");

        publisherStuff.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        publisherStuff.setText("Publisher goes here");

        publishDateStuff.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        publishDateStuff.setText("Date of Publication goes here");

        genreStuff.setFont(new java.awt.Font("Palatino Linotype", 0, 20)); // NOI18N
        genreStuff.setText("Genre goes here");

        javax.swing.GroupLayout bookViewPanelLayout = new javax.swing.GroupLayout(bookViewPanel);
        bookViewPanel.setLayout(bookViewPanelLayout);
        bookViewPanelLayout.setHorizontalGroup(
            bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookViewPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(coverIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookViewPanelLayout.createSequentialGroup()
                        .addComponent(titleLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleStuff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bookViewPanelLayout.createSequentialGroup()
                        .addComponent(authorLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorStuff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bookViewPanelLayout.createSequentialGroup()
                        .addComponent(isbnLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isbnStuff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bookViewPanelLayout.createSequentialGroup()
                        .addComponent(priceLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceStuff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bookViewPanelLayout.createSequentialGroup()
                        .addComponent(publishLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(publisherStuff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bookViewPanelLayout.createSequentialGroup()
                        .addComponent(publishDateLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(publishDateStuff, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))
                    .addGroup(bookViewPanelLayout.createSequentialGroup()
                        .addComponent(genreLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bookViewPanelLayout.createSequentialGroup()
                                .addComponent(addToCartBut, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(genreStuff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        bookViewPanelLayout.setVerticalGroup(
            bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookViewPanelLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLab, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleStuff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(authorLab, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(authorStuff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(isbnLab, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(isbnStuff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(priceLab, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(priceStuff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(publishLab, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(publisherStuff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publishDateLab, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publishDateStuff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genreLab, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genreStuff, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(addToCartBut, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookViewPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(coverIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookViewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addToCartButActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BookView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartBut;
    private javax.swing.JLabel authorLab;
    private javax.swing.JLabel authorStuff;
    private javax.swing.JPanel bookViewPanel;
    private javax.swing.JLabel coverIcon;
    private javax.swing.JLabel genreLab;
    private javax.swing.JLabel genreStuff;
    private javax.swing.JLabel isbnLab;
    private javax.swing.JLabel isbnStuff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel priceLab;
    private javax.swing.JLabel priceStuff;
    private javax.swing.JLabel publishDateLab;
    private javax.swing.JLabel publishDateStuff;
    private javax.swing.JLabel publishLab;
    private javax.swing.JLabel publisherStuff;
    private javax.swing.JLabel titleLab;
    private javax.swing.JLabel titleStuff;
    // End of variables declaration//GEN-END:variables
}
